import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import TracksList from "../components/TracksList";
// import Logo from "../public/logo.png";

const Container = styled.div`
  padding: 0 2rem;
  max-height: 100vh;
  height: 100vh;
  /* overflow: hidden; */
`;

const Main = styled.main`
  display: grid;
  grid-template-columns: auto 1fr 1fr 1fr;
  grid-template-rows: 1fr 1fr 1fr 1fr;
  gap: 0px 0px;
  grid-template-areas:
    "side main main main"
    "side main main main"
    "side main main main"
    "side main main main";

  .side-container {
    grid-area: side;
  }
  .main-container {
    grid-area: main;
    display: flex;
    justify-content: center;
    align-items: center;
    .main-content {
      /* margin: auto; */
      text-align: center;
      h4 {
        margin-bottom: 4px;
      }
      p {
        margin: 4px;
        font-weight: 400;
        opacity: 0.8;
      }
      .image-container {
        padding: 10px;
        border-radius: 5px;
        background-color: #111111;
        img {
          width: 300px;
          height: 300px;
          border-radius: 5px;
        }
      }
    }
  }
`;

export default function Home() {
  const tracks = [
    {
      name: "Home",
      release: "Home EP",
      image:
        "https://firebasestorage.googleapis.com/v0/b/maha-quest-music-player.appspot.com/o/Maha_Quest_Home_EP_Artwork.jpg?alt=media&token=db900d0a-16c5-4278-afea-791877615e22",
    },
    {
      name: "Sorry",
      release: "Home EP",
      image:
        "https://firebasestorage.googleapis.com/v0/b/maha-quest-music-player.appspot.com/o/Maha_Quest_Home_EP_Artwork.jpg?alt=media&token=db900d0a-16c5-4278-afea-791877615e22",
    },
    {
      name: "Numa",
      release: "Home EP",
      image:
        "https://firebasestorage.googleapis.com/v0/b/maha-quest-music-player.appspot.com/o/Maha_Quest_Home_EP_Artwork.jpg?alt=media&token=db900d0a-16c5-4278-afea-791877615e22",
    },
    {
      name: "Weirder",
      release: "Home EP",
      image:
        "https://firebasestorage.googleapis.com/v0/b/maha-quest-music-player.appspot.com/o/Maha_Quest_Home_EP_Artwork.jpg?alt=media&token=db900d0a-16c5-4278-afea-791877615e22",
    },
    {
      name: "Home",
      release: "Home EP",
      image:
        "https://firebasestorage.googleapis.com/v0/b/maha-quest-music-player.appspot.com/o/Maha_Quest_Home_EP_Artwork.jpg?alt=media&token=db900d0a-16c5-4278-afea-791877615e22",
    },
    {
      name: "Sorry",
      release: "Home EP",
      image:
        "https://firebasestorage.googleapis.com/v0/b/maha-quest-music-player.appspot.com/o/Maha_Quest_Home_EP_Artwork.jpg?alt=media&token=db900d0a-16c5-4278-afea-791877615e22",
    },
    {
      name: "Numa",
      release: "Home EP",
      image:
        "https://firebasestorage.googleapis.com/v0/b/maha-quest-music-player.appspot.com/o/Maha_Quest_Home_EP_Artwork.jpg?alt=media&token=db900d0a-16c5-4278-afea-791877615e22",
    },
    {
      name: "Weirder",
      release: "Home EP",
      image:
        "https://firebasestorage.googleapis.com/v0/b/maha-quest-music-player.appspot.com/o/Maha_Quest_Home_EP_Artwork.jpg?alt=media&token=db900d0a-16c5-4278-afea-791877615e22",
    },
  ];

  return (
    <Container>
      <Head>
        <title>Maha Quest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <div className="side-container">
          <Image src="/logo.png" alt="logo" width="200" height="200" />
          {/* <img src={Logo} alt="logo" /> */}
          <TracksList tracks={tracks} />
        </div>
        <div className="main-container">
          <div className="main-content">
            <div className="image-container">
              <img src={tracks[0].image} alt="image" />
            </div>
            <h4>Sorry</h4>
            <p>Home EP</p>
            <p>Maha Quest</p>
          </div>
        </div>
      </Main>

      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main> */}

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </Container>
  );
}
