import React from "react";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import TracksList from "../components/TracksList";
import Playback from "../components/Playback";
import db from "../firebase/firebase";
import { collection, getDocs } from "firebase/firestore";

const Container = styled.div`
  padding: 0 2rem;
  max-height: 100vh;
  height: 100vh;
`;

const Main = styled.main`
  min-height: 100vh;
  display: grid;
  grid-template-columns: auto 1fr 1fr 1fr;
  grid-template-rows: 1fr 1fr 1fr 1fr;
  gap: 0px 0px;
  grid-template-areas:
    "side main main main"
    "side main main main"
    "side main main main"
    "side main main main";

  .side-container {
    grid-area: side;
  }
`;

export default function Home() {
  const [currentSong, setCurrentSong] = React.useState({});
  const [isPlaying, setIsPlaying] = React.useState(false);
  const [duration, setDuration] = React.useState(180);
  const [secondsElapsed, setSecondsElapsed] = React.useState(0);
  const [muted, setMuted] = React.useState(false);
  const [loading, setLoading] = React.useState(true);
  const [tracks, setTracks] = React.useState([]);
  // console.log("tracks ", tracks[0]);

  React.useEffect(() => {
    const fetchData = async () => {
      const songs = [];
      try {
        const querySnapshot = await getDocs(collection(db, "songs"));
        querySnapshot.forEach((doc) => {
          songs.push(doc.data());
        });
        setTracks(songs.slice(0).reverse());
      } catch (err) {
        console.log(err);
      }
    };
    fetchData();
  }, []);

  React.useEffect(() => {
    if (tracks.length > 0) {
      setCurrentSong(tracks[0]);
      setLoading(false);
    }
  }, [tracks]);

  return (
    <Container>
      <Head>
        <title>Maha Quest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading ? null : (
        <Main>
          <div className="side-container">
            <Image src="/logo.png" alt="logo" width="200" height="200" />
            <TracksList
              tracks={tracks}
              setIsPlaying={setIsPlaying}
              setCurrentSong={setCurrentSong}
              setSecondsElapsed={setSecondsElapsed}
            />
          </div>
          <Playback
            duration={duration}
            setDuration={setDuration}
            muted={muted}
            setMuted={setMuted}
            isPlaying={isPlaying}
            setIsPlaying={setIsPlaying}
            currentSong={currentSong}
            setCurrentSong={setCurrentSong}
            secondsElapsed={secondsElapsed}
            setSecondsElapsed={setSecondsElapsed}
            loading={loading}
            tracks={tracks}
          />
        </Main>
      )}
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </Container>
  );
}
